name: Build Web App
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Unzip
        run: |
          rm -rf app
          unzip -o "*.zip" -d app
          ls -la app

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Build Backend
        run: |
          cd app
          REQ=$(find. -name "requirements.txt" | head -n 1)
          echo "Found $REQ"
          pip install -r $REQ

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Build Frontend
        run: |
          cd app
          PKG=$(find. -name "package.json" | head -n 1)
          DIR=$(dirname "$PKG")
          echo "Frontend at $DIR"
          cd $DIR
          npm install
          npm run build

      - uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: app
